spring:
  profiles: dev


  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:~/test1
    username: sa
    password: 
  h2:
      console:
        enabled: true
        path: /h2-console
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
server:
  port: 8080
  
  
logging:
   level:
     org:
      springframework: INFO
   

  
---
    
spring:
   profiles: QA
  
  

  
  
  
simba:
   driver-class-name: 
   url: 
   username: 
   password: 
    #schema: digital
 
  
  #jpa:
   # show-sql: true
   
     
   # properties:
   #   hibernate:
  #      dialect: org.hibernate.dialect.MySQL5Dialect
   #     dialect: org.hibernate.dialect.SparkDialect
  
  
